version: "3.9"
services:
  front:
    build: ./frontend
    ports:
      - "3001:3000"
  back:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "rlt"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
