version: "3.9"
services:
  back:
    build: .
    ports:
      - "3010:3000"
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "rlt"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
